### ISSUE TITLE
Can not work on fedora20 (Gnome 3.10.3)

### ISSUE THREAD

**Issue by ThereAndHere** [Neroth/gnome-shell-extension-weather#190]
Can not work on fedora20 (Gnome 3.10.3)
gnome-session[2949]: (gnome-shell:3104): Gjs-WARNING **: JS ERROR: TypeError: forecastList[(intermediate value)].get_value_update is not a function
gnome-session[2949]: Weather<.loadForecast@/home/T/.local/share/gnome-shell/extensions/weather-extension@xeked.com/extension.js:441
gnome-session[2949]: wrapper@/usr/share/gjs-1.0/lang.js:213
gnome-session[2949]: Weather<.refresh@/home/T/.local/share/gnome-shell/extensions/weather-extension@xeked.com/extension.js:349
thereandhere gnome-session[2949]: wrapper@/usr/share/gjs-1.0/lang.js:213
thereandhere gnome-session[2949]: @/home/T/.local/share/gnome-shell/extensions/weather-extension@xeked.com/extension.js:168
