### ISSUE TITLE
Not working on Gnome 3.32

### ISSUE THREAD

**Issue by Abhinav1217** [Neroth/gnome-shell-extension-weather#250]
I am getting following error on Solus 4 Gnome 3.32.1
```

TypeError: GWeather.Location.new_world is not a function

Stack trace:
  @/home/abhinav/.local/share/gnome-shell/extensions/weather-extension@xeked.com/prefs.js:100:10
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:59:13
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:74:31
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:320:17
  main@resource:///org/gnome/shell/extensionPrefs/main.js:635:5
  @<main>:1:43
  
```

**Comment by Reinis** [comment]
@Neroth 
In my [fork](https://github.com/Reinis/gnome-shell-extension-weather), I have brushed up the extension to work with Gnome 3.32 (should still work with older ones, too, at least a couple versions back); this should fix issues #251 #249 #248 #245:
- Reformat and refactor according to Gnome Shell coding style
- Use ES6 classes and arrow functions
- Add support for variable timer interval (after failed update it retries every 30s for up to 5min, by default — every 5min)
- Fix a bunch of crashes and other misc improvements

**Comment by HinTak** [comment]
It seems to work much  better with gnome-shell 3.34 (no code change in the weather extension, I just upgraded from fedora 30 to 31). I'd still like to know what's broken with gnome-shell 3.32 to cause the #249 .
